import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[rgba(241,242,244)]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
